In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
table = pd.DataFrame(iris.data,columns=iris.feature_names)
table.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [2]:
table['target'] = iris.target
table.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [3]:
x = table.drop(['target'], axis='columns')
y = iris.target

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
dt1 = DecisionTreeClassifier(criterion= 'gini', splitter= 'best', max_depth=2)
dt2 = DecisionTreeClassifier(criterion= 'entropy', splitter= 'best', max_depth=5)
dt3 = DecisionTreeClassifier(criterion= 'gini', splitter= 'random', max_depth= 4)
dt4 = DecisionTreeClassifier(criterion= 'entropy', splitter= 'random', max_depth= 6)

In [7]:
dt1.fit(X_train, y_train)
dt2.fit(X_train, y_train)
dt3.fit(X_train, y_train)
dt4.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, splitter='random')

In [8]:
print('dt1 -> ',dt1.score(X_test, y_test))
print('dt2 -> ',dt2.score(X_test, y_test))
print('dt3 -> ',dt3.score(X_test, y_test))
print('dt4 -> ',dt4.score(X_test, y_test))

dt1 ->  0.9666666666666667
dt2 ->  1.0
dt3 ->  0.9
dt4 ->  0.9666666666666667

In [6]:
dt = DecisionTreeClassifier()

In [7]:
from sklearn.model_selection import GridSearchCV

In [8]:
options = {'criterion': ('gini','entropy'),'splitter': ('best','random'),'max_depth' : list(range(1,7)) }

In [9]:
gs = GridSearchCV(dt,options)
gs.fit(X_train, y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ('gini', 'entropy'),
                         'max_depth': [1, 2, 3, 4, 5, 6],
                         'splitter': ('best', 'random')})

In [10]:
gs.cv_results_['params']

[{'criterion': 'gini', 'max_depth': 1, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 1, 'splitter': 'random'},
 {'criterion': 'gini', 'max_depth': 2, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 2, 'splitter': 'random'},
 {'criterion': 'gini', 'max_depth': 3, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 3, 'splitter': 'random'},
 {'criterion': 'gini', 'max_depth': 4, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 4, 'splitter': 'random'},
 {'criterion': 'gini', 'max_depth': 5, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 5, 'splitter': 'random'},
 {'criterion': 'gini', 'max_depth': 6, 'splitter': 'best'},
 {'criterion': 'gini', 'max_depth': 6, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 1, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 1, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 2, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 2, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 3, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 3, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 4, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 4, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 5, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 5, 'splitter': 'random'},
 {'criterion': 'entropy', 'max_depth': 6, 'splitter': 'best'},
 {'criterion': 'entropy', 'max_depth': 6, 'splitter': 'random'}]

In [11]:
gs.best_params_

{'criterion': 'gini', 'max_depth': 2, 'splitter': 'best'}

In [12]:
scores=gs.cv_results_['mean_test_score']
scores

array([0.69166667, 0.68333333, 0.95      , 0.875     , 0.93333333,
       0.90833333, 0.925     , 0.94166667, 0.925     , 0.89166667,
       0.93333333, 0.925     , 0.69166667, 0.68333333, 0.93333333,
       0.8       , 0.93333333, 0.90833333, 0.91666667, 0.925     ,
       0.925     , 0.95      , 0.94166667, 0.94166667])

In [13]:
import numpy as np
np.argmax(scores)

2

In [15]:
scores[2]

0.95

In [17]:
from sklearn.model_selection import RandomizedSearchCV

In [18]:
dt = DecisionTreeClassifier()

In [19]:
options = {'criterion': ('gini','entropy'),'splitter': ('best','random'),'max_depth' : list(range(1,7)) }

In [20]:
samples = 5  
rs = RandomizedSearchCV(dt, param_distributions=options, n_iter=samples)

In [21]:
rs.fit(X_train, y_train)

RandomizedSearchCV(estimator=DecisionTreeClassifier(), n_iter=5,
                   param_distributions={'criterion': ('gini', 'entropy'),
                                        'max_depth': [1, 2, 3, 4, 5, 6],
                                        'splitter': ('best', 'random')})

In [24]:
rs.cv_results_['params']

[{'splitter': 'random', 'max_depth': 1, 'criterion': 'gini'},
 {'splitter': 'random', 'max_depth': 5, 'criterion': 'entropy'},
 {'splitter': 'best', 'max_depth': 1, 'criterion': 'entropy'},
 {'splitter': 'random', 'max_depth': 5, 'criterion': 'gini'},
 {'splitter': 'best', 'max_depth': 4, 'criterion': 'entropy'}]

In [25]:
rs.best_params_

{'splitter': 'random', 'max_depth': 5, 'criterion': 'gini'}

In [26]:
scores = rs.cv_results_['mean_test_score']
scores

array([0.625     , 0.91666667, 0.69166667, 0.93333333, 0.93333333])

In [27]:
import numpy as np
np.argmax(scores)

3